project:
  type: website
  resources: 
    - "*.mp4"

website:
  navbar: 
    search: true
    left:
      - text: "About Me"
        href: index.ipynb
      - text: "Data Science"
        href: introduction.ipynb
      - text: "Prob. & Stats."
        href: 5100_project_code.ipynb
  
    tools: 
      - icon: github
        url: https://github.com/hannah-hana-kim
      - icon: linkedin
        url: https://www.linkedin.com/in/hannahhanakim/
    title: "HANNAH KIM"

  sidebar:
    - title: "About Me"
      style: "docked"
      contents: 
        - text: "About Me"
          href: index.ipynb
    - title: "Data Science"
      style: "docked"
      contents: 
        - text: Code
          url: https://github.com/anly501/dsan-5000-project-hannah-hana-kim/tree/main/dsan-website/5000-website
        - text: Data
          url: https://github.com/anly501/dsan-5000-project-hannah-hana-kim/tree/main/dsan-website/5000-website/data
        - introduction.ipynb
        - data_gathering.ipynb
        - data_cleaning.ipynb
        - eda/eda.ipynb
        - naive_bayes.ipynb
        - clustering/clustering.ipynb
        - dimensionality_reduction.ipynb
        - decision_trees.ipynb
        - arm.ipynb
        - conclusion.ipynb
    - title: "Prob. & Stats"
      style: "docked"
      contents:
        - 5100_project_code.ipynb
        - 5100_report.ipynb

  favicon: hannah_kim_free_logo.png

format:
  html:
    theme: lumen
    toc: true
bibliography: references.bib


